### PR TITLE
fixes for the passkey   issues/1114 & issues/1113

### LINKED ISSUE #1114: Primary || APP CRASH NOTED || On the other options screen, When the user clicks the "Cancel" button on the passkey dialogue APP CRASHES
**Jenkins Status**

 [](https://devserver3.ustadmobile.com/jenkins/job/primary-passkey-error-showing-correction/)

[](https://devserver3.ustadmobile.com/jenkins/job/primary-passkey-error-showing-correction-End-To-End-Tests/)

**Describe the bug**
 On the other options screen, When the user clicks the "Cancel" button on the passkey dialogue  APP CRASHES

**To Reproduce**
1. Go to New user ->Personal Account -> Choose DOB
2. Accept Terms & Policies ->Enter account details
3. Click on Other options button
4. Click on "Sign-up with passkey"
5. Click cancel on the passkey dialogue button - App crashes

**Expected behavior**
On the other options screen, When the user clicks the "Cancel" button on the passkey dialogue -loging gets cancel, there's no error appears

**Screenshots**

https://github.com/user-attachments/assets/9d43519a-fd99-4915-b6e9-e2fd934f9799

https://github.com/user-attachments/assets/c426a11c-c803-42aa-bc07-8713b3a25d52

### PR DESCRIPTION
**Pull request by Nikunjsharma0**
when user cancel app getting closed
https://github.com/UstadMobile/UstadMobile/issues/1114

when user cancel we dont need to show error messgae

https://github.com/UstadMobile/UstadMobile/issues/1113

### CODE REVIEW

File: core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/signup/OtherSignUpOptionSelectionViewModel.kt [hunk 1]
```diff
@@ -115,47 +115,80 @@ class OtherSignUpOptionSelectionViewModel(
...
+                savePerson,
+                _uiState.value.personPicture
+            )
+        }
+        if (passkeyCreated == null) {
+            snackDispatcher.showSnackBar(Snack(message = systemImpl.getString(MR.strings.sorry_something_went_wrong)))
+            Napier.e { "Error occurred during creating passkey" }
+            return
+        }
+        if (isParent) {
```
Comment (mikedawson) [inline core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/signup/OtherSignUpOptionSelectionViewModel.kt]: These changes appear unrelated to the issues this pull request  is supposed to be addressing

File: core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/account/addaccountselectneworexisting/AddAccountSelectNewOrExistingViewModel.kt [hunk 2]
```diff
@@ -151,7 +151,9 @@ class AddAccountSelectNewOrExistingViewModel(
                     is GetCredentialUseCase.NoCredentialAvailableResult -> {
                         //Do nothing
                     }
-
+                    is GetCredentialUseCase.UserCanceledResult -> {
```
Comment (mikedawson) [inline core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/account/addaccountselectneworexisting/AddAccountSelectNewOrExistingViewModel.kt]: All do nothing cases can be combined using ```,```

File: core/src/commonMain/kotlin/com/ustadmobile/core/domain/credentials/CreatePasskeyUseCase.kt [hunk 3]
```diff
@@ -4,6 +4,28 @@ import com.ustadmobile.core.domain.credentials.passkey.model.AuthenticationRespo
 
 interface CreatePasskeyUseCase {
 
-    suspend operator fun invoke(username:String): AuthenticationResponseJSON
+    sealed class CreateCredentialResult()
```
Comment (mikedawson) [inline core/src/commonMain/kotlin/com/ustadmobile/core/domain/credentials/CreatePasskeyUseCase.kt]: Should be CreatePasskeyResult

File: core/src/commonMain/kotlin/com/ustadmobile/core/domain/credentials/CreatePasskeyUseCase.kt [hunk 4]
```diff
@@ -4,6 +4,28 @@ import com.ustadmobile.core.domain.credentials.passkey.model.AuthenticationRespo
...
+
+    data class CreatePasskeyResult(
```
Comment (mikedawson) [inline core/src/commonMain/kotlin/com/ustadmobile/core/domain/credentials/CreatePasskeyUseCase.kt]: PasskeyCreatedResult

File: core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/person/manageaccount/ManageAccountViewModel.kt [hunk 5]
```diff
@@ -127,20 +128,39 @@ class ManageAccountViewModel(
...
+                when (passkeyCreated) {
+                    is CreatePasskeyUseCase.CreatePasskeyResult -> {
+                        savePassKeyUseCase?.invoke(
+                            passkeyResult = passkeyCreated.authenticationResponseJSON,
+                            person = accountManager.currentUserSession.person
+                        )
+                    }
+
+                    is CreatePasskeyUseCase.Error -> {
+                        snackDispatcher.showSnackBar(Snack(message = passkeyCreated.message.toString()))
```
Comment (mikedawson) [inline core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/person/manageaccount/ManageAccountViewModel.kt]: Snackbar is not suitable for a serious/permanent error. That needs to be displayed on the UI

File: core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/person/manageaccount/ManageAccountViewModel.kt [hunk 6]
```diff
@@ -127,20 +128,39 @@ class ManageAccountViewModel(
...
+                    }
+
+                    is CreatePasskeyUseCase.UserCanceledResult -> {
+                        //do nothing
+                    }
+
+                    null -> {
+                        //do nothing
+                    }
+
```
Comment (mikedawson) [inline core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/person/manageaccount/ManageAccountViewModel.kt]: Remove extra line breaks

File: core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/signup/OtherSignUpOptionSelectionViewModel.kt [hunk 7]
```diff
@@ -115,47 +115,80 @@ class OtherSignUpOptionSelectionViewModel(
...
-       // navController.popBackStack(SignUpViewModel.DEST_NAME,false)
 
     }
+
+
+    private suspend fun onReceivedCreatePasskeyResult(
+        passkeyCreated: AuthenticationResponseJSON,
+        savePerson: Person
+    ) {
+        passkeyCreated?.let {
```
Comment (mikedawson) [inline core/src/commonMain/kotlin/com/ustadmobile/core/viewmodel/signup/OtherSignUpOptionSelectionViewModel.kt]: Authentication response cannot be null - useless extra branches / using ?.let should be removed.

**Comment by mikedawson** [comment]
@Nikunjsharma0 please avoid marking issues as resolved where you were not the reporter of said issue.

**Review by mikedawson — APPROVED** [review]
